// <auto-generated />
namespace MyBudget.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initNewCol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initNewCol));
        
        string IMigrationMetadata.Id
        {
            get { return "202103150744445_initNewCol"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
